const products = [

  {
    id:       'empire-jacket',
    name:     'The Empire Jacket',
    category: 'Fashion · Outerwear',
    filter:   'fashion',
    tag:      'New',
    img:      'images/black empire jacket.png',
    desc:     'A structured statement jacket built for those who walk into every room already owning it. Clean architectural lines, premium fabric, and the unmistakable Îæm precision in every seam.',
    type:     'Outerwear — Jacket',
    colours: [
      { name: 'Coffee Brown', hex: '#4B2E2B', img: 'images/brown empire jacket.jpg' },
      { name: 'Soft Black',   hex: '#1C1412', img: 'images/black empire jacket.png' },
      { name: 'Cream',        hex: '#F5E9E2', img: 'images/cream empire jacket.png' },
      { name: 'Cherry Red',   hex: '#8B0000', img: 'images/burgandy empire jacket.png' },
      { name: 'Navy Blue',    hex: '#000080', img: 'images/navy blue.png' },
      { name: 'Forest Green', hex: '#003314', img: 'images/forest green empire jacket.jpg' }
    ],
    price:    'DM for pricing',
    whatsapp: 'Hi%20%C3%8E%C3%A6m%2C%20I%27d%20like%20to%20order%20The%20Empire%20Jacket.%20Please%20send%20me%20your%20measurement%20guide%20and%20pricing.%20%F0%9F%A4%8E',
    featured: true,
    status:   'available',
    season:   'ss2026'
  },

  {
    id:       'silk-tee',
    name:     'Satin Circuits Tee',
    category: 'Fashion · Wearable',
    filter:   'fashion',
    tag:      'SS26',
    img:      'images/silk t shirt.jpeg',
    desc:     'Where the softness of silk meets the precision of a circuit. A premium tee engineered for comfort without compromising on intention. The tech is in the thinking.',
    type:     'Top — T-Shirt',
    colours: [
      { name: 'Cream',        hex: '#F5E9E2', img: 'images/silk t shirt.jpeg' },
      { name: 'Coffee Brown', hex: '#4B2E2B', img: 'images/coffee brown satin top.png' },
      { name: 'Navy Blue',    hex: '#000080', img: 'images/navy blue satin top.jpg' },
      { name: 'Soft Black',   hex: '#1C1412', img: 'images/black satin stop.png' },
      { name: 'Cherry Red',   hex: '#8B0000', img: 'images/burgandy satin top.jpg' }
    ],
    price:    'DM for pricing',
    whatsapp: 'Hi%20%C3%8E%C3%A6m%2C%20I%27d%20like%20to%20order%20the%20Satin%20Circuits%20Tee.%20Please%20send%20me%20your%20measurement%20guide%20and%20pricing.%20%F0%9F%A4%8E',
    featured: true,
    status:   'available',
    season:   'ss2026'
  },

  {
    id:       'two-piece',
    name:     'Two Piece Set',
    category: 'Fashion · Co-ord',
    filter:   'fashion',
    tag:      'SS26',
    img:      'images/coffee brown 2 piece.jpg',
    desc:     'A structured co-ord set designed as a system — every proportion intentional, every detail earned. Built to be worn with certainty.',
    type:     'Co-ord Set — Top & Trousers',
    colours: [
      { name: 'Coffee Brown', hex: '#4B2E2B', img: 'images/coffee brown 2 piece.jpg' },
      { name: 'Navy Blue',    hex: '#000080', img: 'images/navy blue two piece.png' },
      { name: 'Soft Black',   hex: '#1C1412', img: 'images/soft black 2 piece.png' },
      { name: 'Cherry Red',   hex: '#8B0000', img: 'images/burgandy 2 piece.png' },
      { name: 'Cream', hex: '#F5E9E2', img: 'images/2 piece.jpeg' },
      { name: 'Forest Green', hex: '#003314', img: 'images/forest green 2 piece.png' }
    ],
    price:    'DM for pricing',
    whatsapp: 'Hi%20%C3%8E%C3%A6m%2C%20I%27d%20like%20to%20order%20the%20Two%20Piece%20Set.%20Please%20send%20me%20your%20measurement%20guide%20and%20pricing.%20%F0%9F%A4%8E',
    featured: true,
    status:   'available',
    season:   'ss2026'
  },

  {
    id:       'coffee-trench',
    name:     'Coffee Trench',
    category: 'Fashion · Outerwear',
    filter:   'fashion',
    tag:      null,
    img:      'images/Casaco Trench Longo Minimalista Casual e Elegante de Ajuste Solto com Manga Longa e Dupla Fileira de Botões com Cinto, Cinza Puro, Primavera_Outono_Inverno.jpeg',
    desc:     'A longline trench coat in the brand\'s signature coffee brown. Structured enough to command a room, relaxed enough to move through it with ease.',
    type:     'Outerwear — Trench Coat',
    colours:  [],
    price:    'DM for pricing',
    whatsapp: 'Hi%20%C3%8E%C3%A6m%2C%20I%27d%20like%20to%20order%20the%20Coffee%20Trench.%20Please%20send%20me%20your%20measurement%20guide%20and%20pricing.%20%F0%9F%A4%8E',
    featured: false,
    status:   'available',
    season:   'ss2026'
  },

  {
    id:       'smart-band',
    name:     'Cherry Smart Band',
    category: 'Tech · Wearable',
    filter:   'wearables',
    tag:      null,
    img:      'images/Fitbit Inspire 3.jpeg',
    desc:     'Technology you actually want to wear. Tracks your vitals without announcing itself — minimal design, maximum function.',
    type:     'Accessory — Smart Wearable',
    colours:  [],
    price:    'DM for pricing',
    whatsapp: 'Hi%20%C3%8E%C3%A6m%2C%20I%27d%20like%20to%20order%20the%20Cherry%20Smart%20Band.%20Please%20send%20me%20pricing%20details.%20%F0%9F%A4%8E',
    featured: false,
    status:   'available',
    season:   'ss2026'
  },

  {
    id:       'gold-chain',
    name:     'Imperial Gold Chain',
    category: 'Fashion · Jewellery',
    filter:   'accessories',
    tag:      null,
    img:      'images/14K Solid Gold Franco Chain Necklace_ Diamond Cut Foxtail Design.jpeg',
    desc:     'Not decoration. A statement. The finishing detail that signals everything without saying anything.',
    type:     'Accessory — Jewellery',
    colours:  [],
    price:    'DM for pricing',
    whatsapp: 'Hi%20%C3%8E%C3%A6m%2C%20I%27d%20like%20to%20order%20the%20Imperial%20Gold%20Chain.%20Please%20send%20me%20pricing%20details.%20%F0%9F%A4%8E',
    featured: false,
    status:   'available',
    season:   'ss2026'
  },

  {
    id:       'interface-cap',
    name:     'Interface Cap',
    category: 'Fashion · Accessories',
    filter:   'accessories',
    tag:      'SS26',
    img:      'images/Brand identity & pitch deck design for Soma.jpeg',
    desc:     'The cap that signals everything. Clean construction, considered detail, unmistakable presence.',
    type:     'Accessory — Cap',
    colours:  [],
    price:    'DM for pricing',
    whatsapp: 'Hi%20%C3%8E%C3%A6m%2C%20I%27d%20like%20to%20order%20the%20Interface%20Cap.%20Please%20send%20me%20pricing%20details.%20%F0%9F%A4%8E',
    featured: false,
    status:   'available',
    season:   'ss2026'
  },

  {
    id:       'ankara-gown',
    name:     'Ankara Gown',
    category: 'Fashion · Dresses',
    filter:   'fashion',
    tag:      null,
    img:      'images/Ankara Dress.jpeg',
    desc:     'A stunning Ankara-inspired gown that combines traditional patterns with modern silhouettes.',
    type:     'Dresses — Gown',
    colours:  [],
    price:    'DM for pricing',
    whatsapp: 'Hi%20%C3%8E%C3%A6m%2C%20I%27d%20like%20to%20order%20the%20Ankara%20Gown.%20Please%20send%20me%20pricing%20details.%20%F0%9F%A4%8E',
    featured: false,
    status:   'available',
    season:   'ss2026'
  },

  {
    id:       'lace-high-neck-gown',
    name:     'Lace High Neck Gown',
    category: 'Fashion · Dresses',
    filter:   'fashion',
    tag:      null,
    img:      'images/lace gown.jpeg',
    desc:     'An elegant lace gown with a high neckline, perfect for formal occasions.',
    type:     'Dresses — Gown',
    colours:  [],
    price:    'DM for pricing',
    whatsapp: 'Hi%20%C3%8E%C3%A6m%2C%20I%27d%20like%20to%20order%20the%20Lace%20High%20Neck%20Gown.%20Please%20send%20me%20pricing%20details.%20%F0%9F%A4%8E',
    featured: false,
    status:   'available',
    season:   'ss2026'
  },

  {
    id:       'blazzer-fashion',
    name:     'Blazzer Fashion',
    category: 'Fashion · Outerwear',
    filter:   'fashion',  
    tag:      null,
    img:      'images/blazzer.jpeg',
    desc:     'A stylish blazer that combines classic tailoring with contemporary design elements.',
    type:     'Outerwear — Blazer',
    colours:  [],
    price:    'DM for pricing',
    whatsapp: 'Hi%20%C3%8E%C3%A6m%2C%20I%27d%20like%20to%20order%20the%20Blazzer%20Fashion.%20Please%20send%20me%20pricing%20details.%20%F0%9F%A4%8E',
    featured: false,
    status:   'available',
    season:   'ss2026'
  },

  {
    id:       'asymmetric-rose-gown',
    name:     'Asymmetric Rose Gown',
    category: 'Fashion · Dresses',
    filter:   'fashion',
    tag:      null,
    img:      'images/rose pletteted gown.jpeg',
    desc:     'A beautiful asymmetric gown with a rose-inspired design, perfect for special occasions.',
    type:     'Dresses — Gown',
    colours:  [],
    price:    'DM for pricing',
    whatsapp: 'Hi%20%C3%8E%C3%A6m%2C%20I%27d%20like%20to%20order%20the%20Asymmetric%20Rose%20Gown.%20Please%20send%20me%20pricing%20details.%20%F0%9F%A4%8E',
    featured: false,
    status:   'available',
    season:   'ss2026'
  },

  {
    id:       'prom-gown',
    name:     'Prom Gown',
    category: 'Fashion · Dresses',
    filter:   'fashion',
    tag:      null,
    img:      'images/prom gown.jpeg',
    desc:     'A stunning prom gown that will make you the center of attention.',
    type:     'Dresses — Gown',
    colours:  [],
    price:    'DM for pricing',
    whatsapp: 'Hi%20%C3%8E%C3%A6m%2C%20I%27d%20like%20to%20order%20the%20Prom%20Gown.%20Please%20send%20me%20pricing%20details.%20%F0%9F%A4%8E',
    featured: false,
    status:   'available',
    season:   'ss2026'
  },

  {
    id:       'chiffon-evening-gown',
    name:     'Chiffon Evening Gown',
    category: 'Fashion · Dresses',
    filter:   'fashion',
    tag:      null,
    img:      'images/Chiffon Long Sleeve Dress.jpeg',
    desc:     'A graceful chiffon gown perfect for elegant evening events.',
    type:     'Dresses — Gown',
    colours:  [],
    price:    'DM for pricing',
    whatsapp: 'Hi%20%C3%8E%C3%A6m%2C%20I%27d%20like%20to%20order%20the%20Chiffon%20Evening%20Gown.%20Please%20send%20me%20pricing%20details.%20%F0%9F%A4%8E',
    featured: false,
    status:   'available',
    season:   'ss2026'
  },

  {
    id:       'asymmetric-gown',
    name:     'Asymmetric Gown',
    category: 'Fashion · Dresses',
    filter:   'fashion',
    tag:      null,
    img:      'images/assymetric gown.jpeg',
    desc:     'A modern asymmetric gown with a unique design, perfect for special occasions.',
    type:     'Dresses — Gown',
    colours:  [],
    price:    'DM for pricing',
    whatsapp: 'Hi%20%C3%8E%C3%A6m%2C%20I%27d%20like%20to%20order%20the%20Asymmetric%20Gown.%20Please%20send%20me%20pricing%20details.%20%F0%9F%A4%8E',
    featured: false,
    status:   'available',
    season:   'ss2026'
  },

  {
    id:       'v-neck-button-gown',
    name:     'V-Neck Button Gown',
    category: 'Fashion · Dresses',
    filter:   'fashion',
    tag:      null,
    img:      'images/button down gown.jpeg',
    desc:     'A sophisticated v-neck gown with a button closure, perfect for formal events.',
    type:     'Dresses — Gown',
    colours:  [],
    price:    'DM for pricing',
    whatsapp: 'Hi%20%C3%8E%C3%A6m%2C%20I%27d%20like%20to%20order%20the%20V-Neck%20Button%20Gown.%20Please%20send%20me%20pricing%20details.%20%F0%9F%A4%8E',
    featured: false,
    status:   'available',
    season:   'ss2026'
  },

  {
    id:       'classy-ankara-gown',
    name:     'Classy Ankara Gown',
    category: 'Fashion · Dresses',
    filter:   'fashion',
    tag:      null,
    img:      'images/chic.jpeg',
    desc:     'A stylish ankara gown with a classic design, perfect for formal events.',
    type:     'Dresses — Gown',
    colours:  [],
    price:    'DM for pricing',
    whatsapp: 'Hi%20%C3%8E%C3%A6m%2C%20I%27d%20like%20to%20order%20the%20Classy%20Ankara%20Gown.%20Please%20send%20me%20pricing%20details.%20%F0%9F%A4%8E',
    featured: false,
    status:   'available',
    season:   'ss2026'
  },

  {
    id:       'lace-round-neck-gown',
    name:     'Lace Round Neck Gown',
    category: 'Fashion · Dresses',
    filter:   'fashion',  
    tag:      null,
    img:      'images/round neck lace gown.jpeg',
    desc:     'An elegant lace gown with a round neck design, perfect for formal events.',
    type:     'Dresses — Gown',
    colours:  [],
    price:    'DM for pricing',
    whatsapp: 'Hi%20%C3%8E%C3%A6m%2C%20I%27d%20like%20to%20order%20the%20Lace%20Round%20Neck%20Gown.%20Please%20send%20me%20pricing%20details.%20%F0%9F%A4%8E',
    featured: false,
    status:   'available',
    season:   'ss2026'
  },

  {
    id:       'velvet-evening-gown',
    name:     'Velvet Evening Gown',
    category: 'Fashion · Dresses',
    filter:   'fashion',
    tag:      null,
    img:      'images/velvet evening gown.jpeg',
    desc:     'A luxurious velvet gown perfect for elegant evening events.',
    type:     'Dresses — Gown',
    colours:  [],
    price:    'DM for pricing',
    whatsapp: 'Hi%20%C3%8E%C3%A6m%2C%20I%27d%20like%20to%20order%20the%20Velvet%20Evening%20Gown.%20Please%20send%20me%20pricing%20details.%20%F0%9F%A4%8E',
    featured: false,
    status:   'available',
    season:   'ss2026'
  },

  {
    id:       'v-neck-velvet-gown',
    name:     'V-Neck Velvet Gown',
    category: 'Fashion · Dresses',
    filter:   'fashion',
    tag:      null,
    img:      'images/V-NECK PETAL STRAPLESS VELVET MAXI DRESS IN RED - Burgundy Red _ S.jpeg',
    desc:     'A sophisticated v-neck velvet gown, perfect for formal events.',
    type:     'Dresses — Gown',
    colours:  [],
    price:    'DM for pricing',
    whatsapp: 'Hi%20%C3%8E%C3%A6m%2C%20I%27d%20like%20to%20order%20the%20V-Neck%20Velvet%20Gown.%20Please%20send%20me%20pricing%20details.%20%F0%9F%A4%8E',
    featured: false,
    status:   'available',
    season:   'ss2026'
  },

  {
    id:       'velvet-gown',
    name:     'Velvet Gown',
    category: 'Fashion · Dresses',
    filter:   'fashion',
    tag:      null,
    img:      'images/Burgundy Velvet Long Bridesmaid Dress_ Long Sleeve….jpeg',
    desc:     'A luxurious velvet gown perfect for elegant evening events.',
    type:     'Dresses — Gown',
    colours:  [],
    price:    'DM for pricing',
    whatsapp: 'Hi%20%C3%8E%C3%A6m%2C%20I%27d%20like%20to%20order%20the%20Velvet%20Gown.%20Please%20send%20me%20pricing%20details.%20%F0%9F%A4%8E',
    featured: false,
    status:   'available',
    season:   'ss2026'
  },

  {
    id:       'spring-dress',
    name:     'Spring Dress',
    category: 'Fashion · Dresses',
    filter:   'fashion',
    tag:      null,
    img:      'images/Warm spring retro dress 👗.jpeg',
    desc:     'A warm and retro spring dress, perfect for casual outings.',
    type:     'Dresses — Dress',
    colours:  [],
    price:    'DM for pricing',
    whatsapp: 'Hi%20%C3%8E%C3%A6m%2C%20I%27d%20like%20to%20order%20the%20Spring%20Dress.%20Please%20send%20me%20pricing%20details.%20%F0%9F%A4%8E',
    featured: false,
    status:   'available',
    season:   'ss2026'
  },

  {
    id:       'pink-dress',
    name:     'Pink Dress',
    category: 'Fashion · Dresses',
    filter:   'fashion',
    tag:      null,
    img:      'images/Pink Dress.jpeg',
    desc:     'A beautiful pink dress, perfect for special occasions.',
    type:     'Dresses — Dress',
    colours:  [],
    price:    'DM for pricing',
    whatsapp: 'Hi%20%C3%8E%C3%A6m%2C%20I%27d%20like%20to%20order%20the%20Pink%20Dress.%20Please%20send%20me%20pricing%20details.%20%F0%9F%A4%8E',
    featured: false,
    status:   'available',
    season:   'ss2026'
  },

  {
    id:       'red-dress',
    name:     'Red Dress',
    category: 'Fashion · Dresses',
    filter:   'fashion',
    tag:      null,
    img:      'images/Beautiful Dress by ⚜️ @ulkerhuseynovaofficial ⚜️.jpeg',
    desc:     'A beautiful red dress, perfect for special occasions.',
    type:     'Dresses — Dress',
    colours:  [],
    price:    'DM for pricing',
    whatsapp: 'Hi%20%C3%8E%C3%A6m%2C%20I%27d%20like%20to%20order%20the%20Red%20Dress.%20Please%20send%20me%20pricing%20details.%20%F0%9F%A4%8E',
    featured: false,
    status:   'available',
    season:   'ss2026'
  },

  {
    id:       'mesh-gown',
    name:     'Mesh Gown',
    category: 'Fashion · Dresses',
    filter:   'fashion',
    tag:      null,
    img:      'images/Modern African Print Elegance 🌍 _ Sculpted Fit & Bold Colors.jpeg',
    desc:     'A beautiful mesh gown, perfect for special occasions.',
    type:     'Dresses — Gown',
    colours:  [],
    price:    'DM for pricing',
    whatsapp: 'Hi%20%C3%8E%C3%A6m%2C%20I%27d%20like%20to%20order%20the%20Mesh%20Gown.%20Please%20send%20me%20pricing%20details.%20%F0%9F%A4%8E',
    featured: false,
    status:   'available',
    season:   'ss2026'
  },

  {
    id:       'orbit-two-piece',
    name:     'Orbit Two Piece',
    category: 'Fashion · Two Piece',
    filter:   'fashion',
    tag:      null,
    img:      'images/Orbit.jpeg',
    desc:     'A stunning two-piece set, perfect for special occasions.',
    type:     'Two Piece Set',
    colours:  [],
    price:    'DM for pricing',
    whatsapp: 'Hi%20%C3%8E%C3%A6m%2C%20I%27d%20like%20to%20order%20the%20Orbit%20Two%20Piece.%20Please%20send%20me%20pricing%20details.%20%F0%9F%A4%8E',
    featured: false,
    status:   'available',
    season:   'ss2026'
  },

  {
    id:       'trending-two-piece',
    name:     'Trending Two Piece',
    category: 'Fashion · Two Piece',
    filter:   'fashion',
    tag:      null,
    img:      'images/Trending outfit 2 piece.jpeg',
    desc:     'A stunning two-piece set, perfect for special occasions.',
    type:     'Two Piece Set',
    colours:  [],
    price:    'DM for pricing',
    whatsapp: 'Hi%20%C3%8E%C3%A6m%2C%20I%27d%20like%20to%20order%20the%20Trending%20Two%20Piece.%20Please%20send%20me%20pricing%20details.%20%F0%9F%A4%8E',
    featured: false,
    status:   'available',
    season:   'ss2026'
  },

  {
    id:       'velvet-dress',
    name:     'Velvet Dress',
    category: 'Fashion · Dresses',  
    filter:   'fashion',
    tag:      null,
    img:      'images/Velvet.jpeg',
    desc:     'A luxurious velvet dress, perfect for elegant evening events.',
    type:     'Dresses — Dress',
    colours:  [],
    price:    'DM for pricing',
    whatsapp: 'Hi%20%C3%8E%C3%A6m%2C%20I%27d%20like%20to%20order%20the%20Velvet%20Dress.%20Please%20send%20me%20pricing%20details.%20%F0%9F%A4%8E',
    featured: false,
    status:   'available',
    season:   'ss2026'
  },

  {
    id:       'bubu-gown',
    name:     'Bubu Gown',
    category: 'Fashion · Dresses',
    filter:   'fashion',
    tag:      null,
    img:      'images/761952830752059867.jpeg',
    desc:     'A beautiful bubu gown, perfect for special occasions.',
    type:     'Dresses — Gown',
    colours:  [],
    price:    'DM for pricing',
    whatsapp: 'Hi%20%C3%8E%C3%A6m%2C%20I%27d%20like%20to%20order%20the%20Bubu%20Gown.%20Please%20send%20me%20pricing%20details.%20%F0%9F%A4%8E',
    featured: false,
    status:   'available',
    season:   'ss2026'
  },

  {
    id:       'jumpsuit',
    name:     'Jumpsuit',
    category: 'Fashion · Jumpsuit',
    filter:   'fashion',
    tag:      null,
    img:      'images/782993085259372835.jpeg',
    desc:     'A stylish jumpsuit, perfect for a modern look.',
    type:     'Jumpsuit',
    colours:  [],
    price:    'DM for pricing',
    whatsapp: 'Hi%20%C3%8E%C3%A6m%2C%20I%27d%20like%20to%20order%20the%20Jumpsuit.%20Please%20send%20me%20pricing%20details.%20%F0%9F%A4%8E',
    featured: false,
    status:   'available',
    season:   'ss2026'
  },

  {
    id:       'gingham-gathers',
    name:     'Gingham Gathers',
    category: 'Fashion · Dresses',
    filter:   'fashion',
    tag:      null,
    img:      'images/585819864073883200.jpeg',
    desc:     'A charming gingham dress, perfect for a casual yet stylish look.',
    type:     'Dresses — Dress',
    colours:  [],
    price:    'DM for pricing',
    whatsapp: 'Hi%20%C3%8E%C3%A6m%2C%20I%27d%20like%20to%20order%20the%20Gingham%20Gathers.%20Please%20send%20me%20pricing%20details.%20%F0%9F%A4%8E',
    featured: false,
    status:   'available',
    season:   'ss2026'
  }
];
